import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const authors = ['田中 悠', '佐藤 健', '鈴木 あかり', '山田 拓海', '伊藤 莉奈', '中村 翔', '小林 美咲', '加藤 大輝', '渡辺 さくら', '松本 亮']

const posts = [
  {
    title: 'Dockerネットワークのbridgeとhostモードの違いを理解した',
    summary: 'Docker Composeで複数コンテナが通信できない問題に直面し、bridgeモードとhostモードの挙動の違いを調査して解決した。',
    content: `## 問題\n\ndocker-compose.ymlでAPIサーバーとDBコンテナを定義したが、APIからDBに接続できなかった。\n\n## 原因\n\n\`depends_on\`だけでは通信経路が確立されない。\n\n## 解決策\n\n\`\`\`yaml\nservices:\n  api:\n    networks:\n      - app-net\n  db:\n    networks:\n      - app-net\nnetworks:\n  app-net:\n\`\`\`\n\n同一ネットワークに所属させることで、サービス名でDNS解決できるようになった。\n\n## まとめ\n\nbridgeモードでは明示的にnetworksを設定する必要がある。hostモードはLinuxのみ有効。`,
    tags: JSON.stringify(['Docker', 'Docker Compose', 'ネットワーク', 'インフラ']),
    advice: 'docker-composeではnetworksを明示的に定義する習慣をつけると混乱が減る。',
    likes: 12,
  },
  {
    title: 'TypeScriptのジェネリクスでAPIレスポンスの型を安全に扱う',
    summary: 'fetchのレスポンスをanyで受け取っていたコードをジェネリクスで型安全にリファクタリングした。',
    content: `## 背景\n\nAPIレスポンスを\`any\`で受け取るとランタイムエラーが見つかりにくい。\n\n## 解決策\n\n\`\`\`typescript\nasync function fetchData<T>(url: string): Promise<T> {\n  const res = await fetch(url)\n  if (!res.ok) throw new Error(\`HTTP \${res.status}\`)\n  return res.json() as Promise<T>\n}\n\n// 使用例\nconst user = await fetchData<User>('/api/user/1')\n\`\`\`\n\n## メリット\n\n- IDEの補完が効く\n- 型エラーをコンパイル時に検出できる\n- チーム全体でAPIの形が共有される\n\n## まとめ\n\nジェネリクスを使うことでfetchのラッパーを一つにまとめられる。`,
    tags: JSON.stringify(['TypeScript', 'React', 'API', 'ジェネリクス']),
    advice: 'anyを使いたくなった時はジェネリクスで解決できないか検討する。',
    likes: 18,
  },
  {
    title: 'React useEffectの依存配列を正しく設定してループを防ぐ',
    summary: 'useEffectが無限ループに陥る問題を依存配列の見直しとuseCallbackで解決した。',
    content: `## 症状\n\nuseEffect内でオブジェクトや関数を依存配列に指定すると無限ループが発生した。\n\n## 原因\n\nJavaScriptではオブジェクトは参照比較なので、レンダリングごとに新しい参照になる。\n\n## 解決策\n\n\`\`\`typescript\n// NG: 毎レンダリングで新しいオブジェクト参照\nuseEffect(() => {\n  fetchData(options)\n}, [options]) // optionsがオブジェクトの場合ループ\n\n// OK: useMemoで参照を安定させる\nconst stableOptions = useMemo(() => options, [options.id])\nuseEffect(() => {\n  fetchData(stableOptions)\n}, [stableOptions])\n\`\`\`\n\n## まとめ\n\neslinのexhaustive-depsルールを有効にすると依存配列漏れを防げる。`,
    tags: JSON.stringify(['React', 'TypeScript', 'hooks', 'useEffect']),
    advice: 'eslint-plugin-react-hooksを必ず導入してルールに従う。',
    likes: 24,
  },
  {
    title: 'AWS S3の署名付きURLで一時的なファイルダウンロードを実装',
    summary: 'S3の非公開バケットからファイルを安全にダウンロードさせる署名付きURLの実装方法をまとめた。',
    content: `## 要件\n\n- S3バケットは非公開\n- 認証済みユーザーのみが15分間だけダウンロード可能\n\n## 実装\n\n\`\`\`typescript\nimport { GetObjectCommand, S3Client } from '@aws-sdk/client-s3'\nimport { getSignedUrl } from '@aws-sdk/s3-request-presigner'\n\nconst s3 = new S3Client({ region: 'ap-northeast-1' })\n\nexport async function getDownloadUrl(key: string) {\n  const command = new GetObjectCommand({\n    Bucket: process.env.S3_BUCKET_NAME,\n    Key: key,\n  })\n  return getSignedUrl(s3, command, { expiresIn: 900 })\n}\n\`\`\`\n\n## 注意点\n\nIAMロールにs3:GetObjectの権限が必要。Lambda/EC2ならインスタンスプロファイルを使うべき。\n\n## まとめ\n\n署名付きURLはセキュアで一時的なアクセスを実現できる。`,
    tags: JSON.stringify(['AWS', 'S3', 'TypeScript', 'セキュリティ']),
    advice: 'アクセスキーをコードに直書きせず必ずIAMロールを使う。',
    likes: 31,
  },
  {
    title: 'PostgreSQLのEXPLAIN ANALYZEでN+1問題を発見・解決',
    summary: 'ページ読み込みが遅い原因をEXPLAIN ANALYZEで調査し、N+1クエリをJOINで解消した。',
    content: `## 問題\n\n一覧ページの表示が3秒以上かかっていた。\n\n## 調査\n\n\`\`\`sql\nEXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 1;\n\`\`\`\n\nSeq Scanになっており、user_idにインデックスがなかった。また、ループ内でユーザー情報を別クエリで取得していた（N+1）。\n\n## 解決\n\n\`\`\`sql\n-- インデックス追加\nCREATE INDEX idx_orders_user_id ON orders(user_id);\n\n-- JOINで一括取得\nSELECT o.*, u.name FROM orders o\nJOIN users u ON o.user_id = u.id\nWHERE o.status = 'active';\n\`\`\`\n\n## 結果\n\n3秒 → 120msに改善。\n\n## まとめ\n\nパフォーマンス問題はEXPLAIN ANALYZEで可視化してから対処する。`,
    tags: JSON.stringify(['PostgreSQL', 'SQL', 'パフォーマンス', 'N+1', 'データベース']),
    advice: 'Seq ScanとIndex Scanの違いを理解しておくとパフォーマンス改善が早い。',
    likes: 27,
  },
  {
    title: 'GitHub Actionsで自動テスト＆Dockerイメージビルドを構築',
    summary: 'PRをトリガーにJestテスト実行とDockerイメージのビルドを自動化するCIパイプラインを作成した。',
    content: `## ワークフロー設計\n\nPR作成・更新時に以下を自動実行:\n1. テスト実行\n2. Dockerビルド確認\n\n## 実装\n\n\`\`\`yaml\nname: CI\non:\n  pull_request:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm ci\n      - run: npm test\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: docker build -t app .\n\`\`\`\n\n## ポイント\n\n\`cache: npm\`でnode_modulesをキャッシュすると2回目以降が高速になる。\n\n## まとめ\n\nCIがあるとマージ前に問題を検出できて安心感が違う。`,
    tags: JSON.stringify(['GitHub Actions', 'CI/CD', 'Docker', 'Jest', '自動化']),
    advice: 'キャッシュを積極的に使ってCI実行時間を短縮する。',
    likes: 15,
  },
  {
    title: 'Pythonのasyncio/aiohttpで並列APIリクエストを高速化',
    summary: '同期的に順次実行していたAPI呼び出しをaiohttpで並列化し、処理時間を1/5に短縮した。',
    content: `## 問題\n\n10件のAPIリクエストを順次実行すると10秒かかっていた。\n\n## 解決策\n\n\`\`\`python\nimport asyncio\nimport aiohttp\n\nasync def fetch(session, url):\n    async with session.get(url) as resp:\n        return await resp.json()\n\nasync def fetch_all(urls):\n    async with aiohttp.ClientSession() as session:\n        tasks = [fetch(session, url) for url in urls]\n        return await asyncio.gather(*tasks)\n\nresults = asyncio.run(fetch_all(urls))\n\`\`\`\n\n## 結果\n\n10秒 → 2秒に短縮（ボトルネックが最も遅いAPI次第）。\n\n## 注意\n\n並列数が多すぎると相手サーバーに負荷をかけるのでsemaphoreで制限する。\n\n## まとめ\n\nI/O待ちが多い処理はasyncioで並列化すると劇的に速くなる。`,
    tags: JSON.stringify(['Python', 'asyncio', 'aiohttp', '非同期', 'パフォーマンス']),
    advice: 'asyncio.gatherとsemaphoreの組み合わせが並列API呼び出しの定番パターン。',
    likes: 22,
  },
  {
    title: 'Reactのカスタムフックでフォームバリデーションを共通化',
    summary: '複数ページで重複していたフォームバリデーション処理をカスタムフックに切り出し、再利用性を高めた。',
    content: `## 背景\n\n登録フォーム・編集フォームで同じバリデーションロジックが重複していた。\n\n## カスタムフック実装\n\n\`\`\`typescript\nfunction useForm<T extends Record<string, string>>(initialValues: T) {\n  const [values, setValues] = useState(initialValues)\n  const [errors, setErrors] = useState<Partial<T>>({})\n\n  const validate = (rules: Record<keyof T, (v: string) => string | null>) => {\n    const newErrors: Partial<T> = {}\n    for (const key in rules) {\n      const error = rules[key](values[key])\n      if (error) newErrors[key] = error as T[typeof key]\n    }\n    setErrors(newErrors)\n    return Object.keys(newErrors).length === 0\n  }\n\n  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {\n    setValues(prev => ({ ...prev, [e.target.name]: e.target.value }))\n  }\n\n  return { values, errors, handleChange, validate }\n}\n\`\`\`\n\n## まとめ\n\nカスタムフックはロジックの再利用の最良手段。コンポーネントがシンプルになる。`,
    tags: JSON.stringify(['React', 'TypeScript', 'カスタムフック', 'フォーム']),
    advice: '「同じロジックが2箇所以上ある」と気づいたらカスタムフック化のサイン。',
    likes: 19,
  },
  {
    title: 'Nginxでリバースプロキシを設定してNode.jsアプリを本番公開',
    summary: 'EC2上でNginxをリバースプロキシとして使い、Node.jsアプリへのHTTPSアクセスを実現した手順をまとめた。',
    content: `## 構成\n\n\`インターネット → Nginx(80/443) → Node.js(3000)\`\n\n## Nginx設定\n\n\`\`\`nginx\nserver {\n    listen 80;\n    server_name example.com;\n    return 301 https://$host$request_uri;\n}\n\nserver {\n    listen 443 ssl;\n    server_name example.com;\n    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;\n    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;\n\n    location / {\n        proxy_pass http://localhost:3000;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n    }\n}\n\`\`\`\n\n## SSL証明書\n\nLet's Encryptを使うと無料で取得できる。\n\n\`\`\`bash\ncertbot --nginx -d example.com\n\`\`\`\n\n## まとめ\n\nNginxはリバースプロキシ・静的ファイル配信・ロードバランサとして活躍する万能ツール。`,
    tags: JSON.stringify(['Nginx', 'Node.js', 'AWS', 'EC2', 'HTTPS', 'インフラ']),
    advice: 'proxy_set_headerでX-Real-IPを渡さないとアクセスログが全てNginxのIPになる。',
    likes: 33,
  },
  {
    title: 'Git rebaseでコミット履歴を整理してレビューしやすいPRを作る',
    summary: '作業中に増えた細かいコミットをrebase -iでまとめてレビュアーが読みやすいPRを作る方法をまとめた。',
    content: `## 問題\n\n「WIP」「typo修正」「また修正」などのコミットが積み重なってPRのdiffが追いにくい。\n\n## interactive rebaseで整理\n\n\`\`\`bash\n# 最新5コミットをまとめる\ngit rebase -i HEAD~5\n\n# エディタで pick → squash/fixup に変更\npick abc123 機能追加: ユーザー登録\nsquash def456 WIP\nfixup ghi789 typo修正\n\`\`\`\n\n## squashとfixupの違い\n\n- \`squash\`: コミットメッセージを編集して統合\n- \`fixup\`: メッセージを捨てて前のコミットに吸収\n\n## 注意\n\npushした後のrebaseは強制pushが必要で危険。作業ブランチのみで使う。\n\n## まとめ\n\n「1機能1コミット」を目指すとPRレビューの質が上がる。`,
    tags: JSON.stringify(['Git', 'GitHub', 'コードレビュー', '開発効率']),
    advice: 'rebase -iはmainにマージする前の最後の仕上げとして使う。',
    likes: 14,
  },
  {
    title: 'Next.js App RouterでのServer ComponentとClient Componentの使い分け',
    summary: 'App Routerに移行してServer/Client Componentの境界設計で詰まった経験と解決策をまとめた。',
    content: `## Server Componentでできること・できないこと\n\n**できる**\n- DBへの直接アクセス\n- 環境変数へのアクセス（NEXT_PUBLIC_不要）\n- async/awaitによるデータフェッチ\n\n**できない**\n- useState / useEffect\n- イベントハンドラ\n- ブラウザAPIの使用\n\n## 設計方針\n\n\`\`\`\npage.tsx (Server) → データ取得\n  └─ ProductList.tsx (Server) → 一覧表示\n       └─ AddToCartButton.tsx (Client) → インタラクション\n\`\`\`\n\n## よくある間違い\n\n\`\`\`tsx\n// NG: Server ComponentでuseStateは使えない\nexport default function Page() {\n  const [count, setCount] = useState(0) // エラー\n}\n\n// OK: Clientに分離\n'use client'\nexport function Counter() {\n  const [count, setCount] = useState(0)\n}\n\`\`\`\n\n## まとめ\n\nデフォルトはServerで書き、インタラクションが必要な部分だけClientに切り出す。`,
    tags: JSON.stringify(['Next.js', 'React', 'App Router', 'TypeScript', 'Server Component']),
    advice: '\'use client\'は末端の葉コンポーネントにだけつける設計が理想。',
    likes: 41,
  },
  {
    title: 'Redisでセッション管理とAPIレート制限を実装',
    summary: 'JWTの課題を解決するためRedisをセッションストアとして使い、同時にAPIのレート制限も実装した。',
    content: `## JWTの問題点\n\nJWTはサーバー側でログアウト（無効化）が難しい。\n\n## Redis活用\n\n\`\`\`typescript\nimport { createClient } from 'redis'\n\nconst redis = createClient({ url: process.env.REDIS_URL })\nawait redis.connect()\n\n// セッション保存（1時間で期限切れ）\nawait redis.setEx(\`session:\${sessionId}\`, 3600, userId)\n\n// レート制限（1分間に100リクエストまで）\nconst key = \`rate:\${ip}\`\nconst count = await redis.incr(key)\nif (count === 1) await redis.expire(key, 60)\nif (count > 100) throw new Error('Rate limit exceeded')\n\`\`\`\n\n## まとめ\n\nRedisはセッション・キャッシュ・レート制限の三役をこなせる高速KVS。`,
    tags: JSON.stringify(['Redis', 'Node.js', 'セキュリティ', 'API', 'セッション']),
    advice: 'Redisのデータは再起動で消えるのでセッション以外の永続データはDBに保存する。',
    likes: 28,
  },
  {
    title: 'Pythonのdataclassとpydanticでデータバリデーションを型安全に',
    summary: 'dictで受け取っていたAPIデータをpydanticのBaseModelで型安全に扱うようにリファクタリングした。',
    content: `## 移行前\n\n\`\`\`python\ndef process_user(data: dict):\n    name = data['name']  # KeyError の危険\n    age = int(data['age'])  # 型変換が手動\n\`\`\`\n\n## pydantic導入後\n\n\`\`\`python\nfrom pydantic import BaseModel, field_validator\n\nclass User(BaseModel):\n    name: str\n    age: int\n    email: str\n\n    @field_validator('age')\n    def age_must_be_positive(cls, v):\n        if v < 0:\n            raise ValueError('age must be positive')\n        return v\n\n# FastAPIと組み合わせると自動バリデーション\n@app.post('/users')\ndef create_user(user: User):  # リクエストボディを自動パース\n    return user\n\`\`\`\n\n## まとめ\n\npydanticはFastAPIと相性抜群。バリデーション・シリアライズが自動化される。`,
    tags: JSON.stringify(['Python', 'pydantic', 'FastAPI', '型安全', 'バリデーション']),
    advice: 'FastAPIを使うならpydanticは必須セット。最初から使い始める。',
    likes: 20,
  },
  {
    title: 'Terraformでインフラをコード管理してチーム開発を効率化',
    summary: 'クリックベースのAWS設定管理からTerraformに移行し、インフラ変更をGitで管理できるようにした。',
    content: `## 導入前の問題\n\n- 誰がいつ何を変更したか不明\n- 本番と開発環境の差分が不明\n- 環境の再現が手作業で大変\n\n## Terraform基本構成\n\n\`\`\`hcl\nprovider "aws" {\n  region = "ap-northeast-1"\n}\n\nresource "aws_instance" "web" {\n  ami           = "ami-0123456789"\n  instance_type = "t3.micro"\n  tags = {\n    Name = "web-server"\n    Env  = var.environment\n  }\n}\n\noutput "public_ip" {\n  value = aws_instance.web.public_ip\n}\n\`\`\`\n\n## 運用フロー\n\n\`\`\`bash\nterraform plan   # 変更内容を確認\nterraform apply  # 適用\n\`\`\`\n\n## まとめ\n\nIaCにするとインフラをコードレビューできる。チーム開発では必須。`,
    tags: JSON.stringify(['Terraform', 'AWS', 'IaC', 'インフラ', 'DevOps']),
    advice: 'terraform planの結果をPRコメントに貼るとレビューが楽になる。',
    likes: 36,
  },
  {
    title: 'MySQLのインデックス設計でクエリを100倍速くした',
    summary: 'WHERE句とORDER BYの複合インデックスを設計し、フルスキャンを解消してレスポンスを大幅改善した。',
    content: `## 問題のクエリ\n\n\`\`\`sql\nSELECT * FROM articles\nWHERE category = 'tech' AND status = 'published'\nORDER BY created_at DESC\nLIMIT 20;\n\`\`\`\n\n実行時間: 2.3秒（articles: 100万件）\n\n## EXPLAIN確認\n\n\`\`\`sql\nEXPLAIN SELECT ...\n-- type: ALL（フルスキャン）\n-- rows: 1,000,000\n\`\`\`\n\n## 複合インデックスを追加\n\n\`\`\`sql\n-- WHERE句 + ORDER BYをカバーする複合インデックス\nCREATE INDEX idx_articles_category_status_created\nON articles(category, status, created_at DESC);\n\`\`\`\n\n実行時間: 0.02秒（100倍改善）\n\n## ポイント\n\n複合インデックスのカラム順序はWHEREの等値条件 → 範囲条件 → ORDER BYの順が基本。\n\n## まとめ\n\nインデックスはEXPLAINを見ながら追加するのが正しいアプローチ。`,
    tags: JSON.stringify(['MySQL', 'SQL', 'インデックス', 'パフォーマンス', 'データベース']),
    advice: 'インデックスは貼りすぎるとINSERT/UPDATEが遅くなる。必要なものだけ追加する。',
    likes: 45,
  },
  {
    title: 'Jestでモックを使ったユニットテストの書き方',
    summary: '外部APIやDBへの依存をモックで切り離してユニットテストを書く方法を整理した。',
    content: `## モックの必要性\n\nユニットテストはDBやAPIに依存しないのが理想。\n\n## jest.mockの使い方\n\n\`\`\`typescript\n// userService.test.ts\nimport { getUserById } from './userService'\nimport { prisma } from './prismaClient'\n\njest.mock('./prismaClient', () => ({\n  prisma: {\n    user: {\n      findUnique: jest.fn(),\n    },\n  },\n}))\n\ntest('ユーザーが存在する場合にデータを返す', async () => {\n  const mockUser = { id: '1', name: 'テスト太郎' }\n  ;(prisma.user.findUnique as jest.Mock).mockResolvedValue(mockUser)\n\n  const result = await getUserById('1')\n  expect(result).toEqual(mockUser)\n})\n\ntest('ユーザーが存在しない場合にnullを返す', async () => {\n  ;(prisma.user.findUnique as jest.Mock).mockResolvedValue(null)\n\n  const result = await getUserById('999')\n  expect(result).toBeNull()\n})\n\`\`\`\n\n## まとめ\n\nモックを使うとDBなしで速くテストを実行できる。`,
    tags: JSON.stringify(['Jest', 'TypeScript', 'テスト', 'モック', 'ユニットテスト']),
    advice: 'テストが書きにくい = 設計が複雑なサインと捉えると良い。',
    likes: 17,
  },
  {
    title: 'CSSのGrid Layoutでレスポンシブなカードレイアウトを実装',
    summary: 'メディアクエリなしでCSS Gridのauto-fillを使ったレスポンシブカードレイアウトを実装した。',
    content: `## 実装\n\n\`\`\`css\n.card-grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));\n  gap: 1.5rem;\n}\n\`\`\`\n\n## auto-fillとauto-fitの違い\n\n- \`auto-fill\`: 空のトラックも確保（グリッド幅を維持）\n- \`auto-fit\`: 空のトラックを折りたたむ（アイテムを引き伸ばす）\n\n少数アイテムで画面幅いっぱいに広げたい場合は\`auto-fit\`が適切。\n\n## メリット\n\nメディアクエリなしで画面幅に応じて1〜4列を自動調整。\n\n## まとめ\n\n\`repeat(auto-fill, minmax())\`パターンを覚えるだけでレスポンシブグリッドが完成する。`,
    tags: JSON.stringify(['CSS', 'Grid', 'レスポンシブ', 'フロントエンド']),
    advice: 'Flexboxは1方向、Gridは2方向のレイアウト。用途に合わせて選ぶ。',
    likes: 16,
  },
  {
    title: 'Kubernetesでアプリをデプロイしてローリングアップデートを体験',
    summary: 'k8sのDeploymentリソースを使って本番無停止でのアプリ更新を実現した手順をまとめた。',
    content: `## Deployment定義\n\n\`\`\`yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web-app\nspec:\n  replicas: 3\n  strategy:\n    type: RollingUpdate\n    rollingUpdate:\n      maxSurge: 1\n      maxUnavailable: 0\n  selector:\n    matchLabels:\n      app: web\n  template:\n    metadata:\n      labels:\n        app: web\n    spec:\n      containers:\n        - name: web\n          image: myapp:v2\n          ports:\n            - containerPort: 3000\n          readinessProbe:\n            httpGet:\n              path: /health\n              port: 3000\n            initialDelaySeconds: 5\n\`\`\`\n\n## ポイント\n\n\`readinessProbe\`を設定しないと起動中のPodにトラフィックが来てしまう。\n\n## まとめ\n\nrollingUpdateとreadinessProbeの組み合わせで無停止デプロイが実現できる。`,
    tags: JSON.stringify(['Kubernetes', 'k8s', 'Docker', 'インフラ', 'DevOps']),
    advice: 'readinessProbeとlivenessProbeは必ず設定する。本番事故を防ぐ最重要設定。',
    likes: 39,
  },
  {
    title: 'OpenAI APIでチャットアプリを作る際のストリーミング実装',
    summary: 'ChatGPTのようなストリーミング表示をOpenAI APIのstream optionで実装した方法をまとめた。',
    content: `## 通常レスポンスの問題\n\n全文生成まで待つと長文の場合にUXが悪い。\n\n## ストリーミング実装\n\n\`\`\`typescript\nimport OpenAI from 'openai'\n\nconst openai = new OpenAI()\n\nexport async function* streamChat(message: string) {\n  const stream = await openai.chat.completions.create({\n    model: 'gpt-4o-mini',\n    messages: [{ role: 'user', content: message }],\n    stream: true,\n  })\n\n  for await (const chunk of stream) {\n    const text = chunk.choices[0]?.delta?.content ?? ''\n    if (text) yield text\n  }\n}\n\n// Next.js Route Handler\nexport async function POST(req: Request) {\n  const { message } = await req.json()\n  const encoder = new TextEncoder()\n  const readable = new ReadableStream({\n    async start(controller) {\n      for await (const text of streamChat(message)) {\n        controller.enqueue(encoder.encode(text))\n      }\n      controller.close()\n    },\n  })\n  return new Response(readable)\n}\n\`\`\`\n\n## まとめ\n\nストリーミングはReadableStreamとfor-awaitの組み合わせで実装できる。`,
    tags: JSON.stringify(['OpenAI', 'AI', 'TypeScript', 'Next.js', 'ストリーミング']),
    advice: 'ストリーミングはUXを大幅に改善するが、エラーハンドリングが複雑になる点に注意。',
    likes: 52,
  },
  {
    title: 'ESLintとPrettierをVSCodeで連携させてコードを自動整形',
    summary: 'チームで統一されたコードスタイルを強制するためにESLint + Prettierをhusky pre-commitフックで設定した。',
    content: `## 設定ファイル\n\n\`\`\`json\n// .eslintrc.json\n{\n  "extends": ["next/core-web-vitals", "prettier"],\n  "rules": {\n    "no-unused-vars": "error",\n    "no-console": "warn"\n  }\n}\n\n// .prettierrc\n{\n  "semi": false,\n  "singleQuote": true,\n  "tabWidth": 2,\n  "trailingComma": "all"\n}\n\`\`\`\n\n## huskyでpre-commit設定\n\n\`\`\`bash\nnpm install --save-dev husky lint-staged\nnpx husky init\n\`\`\`\n\n\`\`\`json\n// package.json\n{\n  "lint-staged": {\n    "*.{ts,tsx}": ["eslint --fix", "prettier --write"]\n  }\n}\n\`\`\`\n\n## まとめ\n\nコミット時に自動整形されるので「フォーマットを忘れた」系のPRコメントが激減した。`,
    tags: JSON.stringify(['ESLint', 'Prettier', 'TypeScript', 'Git', '開発環境']),
    advice: 'チーム全員が同じVSCode設定を共有するために.vscode/settings.jsonをGitで管理する。',
    likes: 23,
  },
  {
    title: 'WebSocketでリアルタイム通知機能を実装',
    summary: 'Socket.ioを使ってサーバーからクライアントへのプッシュ通知を実装した。ポーリングから置き換えてサーバー負荷を削減した。',
    content: `## ポーリングの問題\n\n毎秒APIを叩くポーリングはサーバーに無駄な負荷をかける。\n\n## Socket.io実装\n\n\`\`\`typescript\n// サーバー\nimport { Server } from 'socket.io'\n\nconst io = new Server(httpServer, {\n  cors: { origin: process.env.CLIENT_URL }\n})\n\nio.on('connection', (socket) => {\n  console.log('connected:', socket.id)\n\n  socket.on('join', (userId: string) => {\n    socket.join(\`user:\${userId}\`)\n  })\n})\n\n// 通知を送信\nfunction notifyUser(userId: string, message: string) {\n  io.to(\`user:\${userId}\`).emit('notification', { message })\n}\n\`\`\`\n\n\`\`\`typescript\n// クライアント (React)\nimport { useEffect } from 'react'\nimport io from 'socket.io-client'\n\nconst socket = io(process.env.NEXT_PUBLIC_WS_URL)\n\nuseEffect(() => {\n  socket.emit('join', userId)\n  socket.on('notification', (data) => {\n    toast(data.message)\n  })\n  return () => { socket.off('notification') }\n}, [userId])\n\`\`\`\n\n## まとめ\n\nリアルタイム性が必要な機能はWebSocketを使うとサーバー負荷とUXの両方を改善できる。`,
    tags: JSON.stringify(['WebSocket', 'Socket.io', 'Node.js', 'React', 'リアルタイム']),
    advice: 'WebSocketは接続数が増えると負荷が大きいのでRedis AdapterでスケールアウトをURLに設計する。',
    likes: 30,
  },
  {
    title: 'Prismaのトランザクションで複数テーブルの整合性を保つ',
    summary: '注文処理で在庫更新と注文作成を同時に行う際、トランザクションで整合性を担保した実装例をまとめた。',
    content: `## 問題\n\n在庫を減らした後、注文作成に失敗すると在庫だけが減る不整合が起きる。\n\n## トランザクション実装\n\n\`\`\`typescript\nasync function createOrder(userId: string, productId: string, qty: number) {\n  return prisma.$transaction(async (tx) => {\n    // 在庫確認\n    const product = await tx.product.findUnique({\n      where: { id: productId }\n    })\n    if (!product || product.stock < qty) {\n      throw new Error('在庫不足')\n    }\n\n    // 在庫を減らす\n    await tx.product.update({\n      where: { id: productId },\n      data: { stock: { decrement: qty } }\n    })\n\n    // 注文を作成\n    return tx.order.create({\n      data: { userId, productId, quantity: qty }\n    })\n  })\n}\n\`\`\`\n\nエラーが発生すると両方のクエリがロールバックされる。\n\n## まとめ\n\n複数テーブルを同時更新する処理は必ずトランザクションで囲む。`,
    tags: JSON.stringify(['Prisma', 'PostgreSQL', 'TypeScript', 'トランザクション', 'データベース']),
    advice: '$transactionは失敗したら全部ロールバックされるので安心して使える。',
    likes: 25,
  },
  {
    title: 'Tailwind CSSのcnユーティリティで条件付きスタイルをすっきり書く',
    summary: 'clsxとtailwind-mergeを組み合わせたcnヘルパーで条件付きclassNameの記述を整理した。',
    content: `## 問題\n\n\`\`\`tsx\n// 読みにくい\n<button className={\`px-4 py-2 rounded \${isActive ? 'bg-blue-500 text-white' : 'bg-gray-200'} \${disabled ? 'opacity-50 cursor-not-allowed' : ''}\`}>\n\`\`\`\n\n## cnヘルパーを定義\n\n\`\`\`typescript\nimport { clsx, type ClassValue } from 'clsx'\nimport { twMerge } from 'tailwind-merge'\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs))\n}\n\`\`\`\n\n## 使用例\n\n\`\`\`tsx\n<button\n  className={cn(\n    'px-4 py-2 rounded',\n    isActive && 'bg-blue-500 text-white',\n    !isActive && 'bg-gray-200',\n    disabled && 'opacity-50 cursor-not-allowed'\n  )}\n>\n\`\`\`\n\n## twMergeが必要な理由\n\nclsxだけだと\`bg-blue-500 bg-red-500\`のような競合するクラスが両方出力される。twMergeが後者を優先してくれる。\n\n## まとめ\n\ncnはTailwindを使うプロジェクトで最初に定義すべきユーティリティ。`,
    tags: JSON.stringify(['Tailwind CSS', 'React', 'TypeScript', 'フロントエンド']),
    advice: 'shadcn/uiを使うと最初からcnが用意されている。',
    likes: 21,
  },
  {
    title: 'Lambda@EdgeでCDNレイヤーでの認証を実装',
    summary: 'CloudFrontのLambda@Edgeを使ってOriginに到達する前にJWT認証を行い、不正アクセスをエッジで遮断した。',
    content: `## 構成\n\n\`クライアント → CloudFront → Lambda@Edge（認証） → S3/ALB\`\n\n## Lambda@Edge関数\n\n\`\`\`javascript\nconst jwt = require('jsonwebtoken')\n\nexports.handler = async (event) => {\n  const request = event.Records[0].cf.request\n  const headers = request.headers\n\n  const authHeader = headers.authorization?.[0]?.value\n  if (!authHeader?.startsWith('Bearer ')) {\n    return { status: '401', body: 'Unauthorized' }\n  }\n\n  try {\n    const token = authHeader.slice(7)\n    jwt.verify(token, process.env.JWT_SECRET)\n    return request // 認証OK → Originに転送\n  } catch {\n    return { status: '403', body: 'Forbidden' }\n  }\n}\n\`\`\`\n\n## 注意点\n\nLambda@Edgeはus-east-1リージョンにのみデプロイ可能。\n\n## まとめ\n\nエッジ認証でOriginへの不正リクエストを根本から防げる。`,
    tags: JSON.stringify(['AWS', 'Lambda', 'CloudFront', 'CDN', 'セキュリティ']),
    advice: 'Lambda@Edgeのコールドスタートは通常Lambdaより遅い場合があるため計測する。',
    likes: 29,
  },
  {
    title: 'GraphQLのN+1問題をDataLoaderで解決',
    summary: 'GraphQL resolverでN+1クエリが発生していた問題をDataLoaderのバッチ処理で解決した。',
    content: `## 問題\n\n\`\`\`graphql\nquery {\n  posts {\n    title\n    author { name }  # 投稿ごとにauthorクエリが走る\n  }\n}\n\`\`\`\n\n100投稿あると101クエリが発生する。\n\n## DataLoaderで解決\n\n\`\`\`typescript\nimport DataLoader from 'dataloader'\n\nconst userLoader = new DataLoader(async (ids: readonly string[]) => {\n  const users = await prisma.user.findMany({\n    where: { id: { in: [...ids] } }\n  })\n  return ids.map(id => users.find(u => u.id === id) ?? null)\n})\n\n// Resolver\nconst resolvers = {\n  Post: {\n    author: (post) => userLoader.load(post.authorId)\n  }\n}\n\`\`\`\n\nDataLoaderはリクエスト内のIDをバッチ化してまとめてクエリする。\n\n## まとめ\n\nGraphQLを使うならDataLoaderはほぼ必須。最初から設計に組み込む。`,
    tags: JSON.stringify(['GraphQL', 'DataLoader', 'Node.js', 'TypeScript', 'パフォーマンス']),
    advice: 'DataLoaderのインスタンスはリクエストごとに作成する（グローバルにするとキャッシュが混在する）。',
    likes: 34,
  },
  {
    title: 'Dockerのマルチステージビルドで本番イメージを軽量化',
    summary: 'マルチステージビルドを使ってNode.jsアプリのDockerイメージを1.2GBから180MBに削減した。',
    content: `## 問題\n\nビルドツールや開発依存を含む大きなイメージが本番環境に展開されていた。\n\n## マルチステージビルド\n\n\`\`\`dockerfile\n# ステージ1: ビルド\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\n# ステージ2: 本番（ビルド成果物だけコピー）\nFROM node:20-alpine AS runner\nWORKDIR /app\nENV NODE_ENV=production\nCOPY package*.json ./\nRUN npm ci --production\nCOPY --from=builder /app/dist ./dist\nEXPOSE 3000\nCMD ["node", "dist/index.js"]\n\`\`\`\n\n## 結果\n\n1.2GB → 180MB（85%削減）\n\n## まとめ\n\nマルチステージビルドは本番イメージに必要なものだけを残せる。起動も速くなる。`,
    tags: JSON.stringify(['Docker', 'Node.js', 'インフラ', 'パフォーマンス', 'CI/CD']),
    advice: 'alpine系のベースイメージを使うとさらに軽量になる。',
    likes: 43,
  },
  {
    title: 'Zustandで軽量なグローバル状態管理を実現',
    summary: 'ReduxからZustandに移行してボイラープレートを大幅に削減した。セレクターパターンも含めて解説。',
    content: `## Reduxとの比較\n\nReduxは設定が多くシンプルな状態管理に向かない。\n\n## Zustandの実装\n\n\`\`\`typescript\nimport { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\n\ninterface AuthStore {\n  user: User | null\n  setUser: (user: User | null) => void\n  logout: () => void\n}\n\nconst useAuthStore = create<AuthStore>()(\n  persist(\n    (set) => ({\n      user: null,\n      setUser: (user) => set({ user }),\n      logout: () => set({ user: null }),\n    }),\n    { name: 'auth-storage' }  // localStorageに永続化\n  )\n)\n\n// 使用\nconst user = useAuthStore((state) => state.user)  // セレクター\nconst logout = useAuthStore((state) => state.logout)\n\`\`\`\n\n## まとめ\n\nZustandはReduxの1/10のコード量で同等の状態管理ができる。`,
    tags: JSON.stringify(['React', 'Zustand', 'TypeScript', '状態管理', 'フロントエンド']),
    advice: 'persistミドルウェアでlocalStorageへの永続化が数行で実現できる。',
    likes: 37,
  },
  {
    title: 'AWS CloudWatchでアプリのメトリクス監視とアラートを設定',
    summary: 'EC2のCPU使用率とALBのエラーレートにCloudWatchアラームを設定し、Slack通知と連携した。',
    content: `## 監視設定\n\n\`\`\`bash\n# CPU使用率が5分間80%超でアラーム\naws cloudwatch put-metric-alarm \\\n  --alarm-name high-cpu \\\n  --metric-name CPUUtilization \\\n  --namespace AWS/EC2 \\\n  --statistic Average \\\n  --period 300 \\\n  --threshold 80 \\\n  --comparison-operator GreaterThanThreshold \\\n  --evaluation-periods 1 \\\n  --alarm-actions arn:aws:sns:...:notify-slack\n\`\`\`\n\n## Slack連携\n\nSNS → Lambda → Slack Webhook で通知。\n\n\`\`\`python\nimport json\nimport urllib.request\n\ndef lambda_handler(event, context):\n    message = event['Records'][0]['Sns']['Message']\n    payload = json.dumps({'text': f'🚨 アラーム: {message}'})\n    req = urllib.request.Request(\n        os.environ['SLACK_WEBHOOK_URL'],\n        data=payload.encode(),\n        headers={'Content-Type': 'application/json'}\n    )\n    urllib.request.urlopen(req)\n\`\`\`\n\n## まとめ\n\n監視なき本番運用は危険。最低限CPUとエラーレートのアラームは設定する。`,
    tags: JSON.stringify(['AWS', 'CloudWatch', 'Slack', 'Lambda', '監視', 'インフラ']),
    advice: 'アラームはうるさすぎると無視されるようになる。閾値は運用しながら調整する。',
    likes: 26,
  },
  {
    title: 'React Server ComponentsとSuspenseで段階的なローディングを実装',
    summary: 'Suspense境界を使って重いコンポーネントのローディングを分離し、ページの体感速度を改善した。',
    content: `## 実装\n\n\`\`\`tsx\nimport { Suspense } from 'react'\n\nexport default function DashboardPage() {\n  return (\n    <div>\n      {/* 即座に表示 */}\n      <Header />\n\n      {/* データ取得中はスケルトンを表示 */}\n      <Suspense fallback={<StatsSkeleton />}>\n        <StatsSection />\n      </Suspense>\n\n      <div className="grid grid-cols-2 gap-4">\n        <Suspense fallback={<ChartSkeleton />}>\n          <SalesChart />\n        </Suspense>\n        <Suspense fallback={<ListSkeleton />}>\n          <RecentOrders />\n        </Suspense>\n      </div>\n    </div>\n  )\n}\n\n// 非同期Server Component\nasync function StatsSection() {\n  const stats = await getStats()  // DB直接呼び出し\n  return <StatsDisplay data={stats} />\n}\n\`\`\`\n\n## まとめ\n\nSuspenseで部分的なローディングが実現でき、ページ全体が固まる問題を解消できる。`,
    tags: JSON.stringify(['React', 'Next.js', 'Suspense', 'UX', 'パフォーマンス']),
    advice: 'Suspense境界は細かく分けるほど体感速度が上がる。',
    likes: 32,
  },
  {
    title: 'Vitestで高速なフロントエンドテスト環境を構築',
    summary: 'JestからVitestに移行してテスト実行時間を60%短縮した。設定ファイルの違いと移行のポイントをまとめた。',
    content: `## なぜVitestか\n\n- Viteと同じ設定ファイルを使える\n- Jestより高速（ESネイティブ）\n- TypeScriptの設定が楽\n\n## 設定\n\n\`\`\`typescript\n// vite.config.ts\nimport { defineConfig } from 'vitest/config'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n  test: {\n    environment: 'jsdom',\n    globals: true,\n    setupFiles: './src/test/setup.ts',\n  },\n})\n\`\`\`\n\n## テストの書き方（Jestとほぼ同じ）\n\n\`\`\`typescript\nimport { render, screen } from '@testing-library/react'\nimport { describe, it, expect } from 'vitest'\nimport Button from './Button'\n\ndescribe('Button', () => {\n  it('テキストを表示する', () => {\n    render(<Button>クリック</Button>)\n    expect(screen.getByText('クリック')).toBeInTheDocument()\n  })\n})\n\`\`\`\n\n## まとめ\n\nViteプロジェクトなら最初からVitestを選ぶべき。移行コストも低い。`,
    tags: JSON.stringify(['Vitest', 'TypeScript', 'React', 'テスト', 'Vite']),
    advice: 'testing-library/user-eventも合わせて導入するとUIのインタラクションテストが楽になる。',
    likes: 18,
  },
  {
    title: 'PostgreSQLのJSONBカラムで柔軟なデータ構造を実現',
    summary: '固定スキーマでは対応しきれない動的なメタデータをJSONBカラムで管理し、GINインデックスで検索を高速化した。',
    content: `## JSONBの活用\n\n\`\`\`sql\nALTER TABLE products ADD COLUMN metadata JSONB;\n\nINSERT INTO products (name, metadata) VALUES\n  ('iPhone 15', '{"color": "black", "storage": "256GB", "warranty": 12}'),\n  ('MacBook', '{"cpu": "M3", "ram": "16GB", "display": "14inch"}');\n\n-- JSONBのキーで検索\nSELECT * FROM products\nWHERE metadata->>'color' = 'black';\n\n-- 数値比較\nSELECT * FROM products\nWHERE (metadata->>'warranty')::int > 6;\n\`\`\`\n\n## GINインデックスで高速化\n\n\`\`\`sql\nCREATE INDEX idx_products_metadata ON products USING GIN(metadata);\n\n-- @> 演算子でインデックスが効く\nSELECT * FROM products\nWHERE metadata @> '{"color": "black"}';\n\`\`\`\n\n## まとめ\n\nJSONBはスキーマレスの柔軟性とSQLの強力なクエリ機能を両立できる。`,
    tags: JSON.stringify(['PostgreSQL', 'JSONB', 'SQL', 'データベース', 'インデックス']),
    advice: '->>は文字列返却、->はJSON返却。型に注意して使い分ける。',
    likes: 22,
  },
  {
    title: 'Slack Botをslack-boltで実装してチームの日次レポートを自動化',
    summary: '毎朝9時にGitHubのPR状況をSlackに通知するBotをslack-boltとGitHub APIで実装した。',
    content: `## 実装\n\n\`\`\`typescript\nimport { App } from '@slack/bolt'\nimport { Octokit } from '@octokit/rest'\n\nconst app = new App({\n  token: process.env.SLACK_BOT_TOKEN,\n  signingSecret: process.env.SLACK_SIGNING_SECRET,\n})\n\nconst octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })\n\nasync function sendDailyReport() {\n  const { data: prs } = await octokit.pulls.list({\n    owner: 'myorg',\n    repo: 'myapp',\n    state: 'open',\n  })\n\n  const message = prs.map(pr =>\n    \`• <\${pr.html_url}|\${pr.title}> by \${pr.user?.login}\`\n  ).join('\\n')\n\n  await app.client.chat.postMessage({\n    channel: '#dev',\n    text: \`📋 *オープンPR一覧（\${prs.length}件）*\\n\${message}\`,\n  })\n}\n\n// cron設定（毎朝9時）\nimport cron from 'node-cron'\ncron.schedule('0 9 * * 1-5', sendDailyReport)\n\`\`\`\n\n## まとめ\n\nSlack BotとGitHub APIを組み合わせると開発チームの情報共有を自動化できる。`,
    tags: JSON.stringify(['Slack', 'GitHub', 'Node.js', 'TypeScript', '自動化', 'Bot']),
    advice: 'BotのトークンはSlack管理画面のOAuth & Permissionsから取得する。スコープ設定を忘れずに。',
    likes: 35,
  },
  {
    title: 'useReducerとContextで中規模アプリの状態管理を整理',
    summary: 'propバケツリレーが深くなってきたタイミングでuseReducer + Contextパターンに移行した手順をまとめた。',
    content: `## パターン\n\n\`\`\`typescript\n// types\ntype Action =\n  | { type: 'SET_USER'; payload: User }\n  | { type: 'LOGOUT' }\n  | { type: 'SET_LOADING'; payload: boolean }\n\ntype State = {\n  user: User | null\n  loading: boolean\n}\n\n// reducer\nfunction reducer(state: State, action: Action): State {\n  switch (action.type) {\n    case 'SET_USER': return { ...state, user: action.payload }\n    case 'LOGOUT': return { ...state, user: null }\n    case 'SET_LOADING': return { ...state, loading: action.payload }\n    default: return state\n  }\n}\n\n// Context\nconst AppContext = createContext<{ state: State; dispatch: Dispatch<Action> } | null>(null)\n\nexport function AppProvider({ children }: { children: ReactNode }) {\n  const [state, dispatch] = useReducer(reducer, { user: null, loading: false })\n  return <AppContext.Provider value={{ state, dispatch }}>{children}</AppContext.Provider>\n}\n\nexport const useAppContext = () => {\n  const ctx = useContext(AppContext)\n  if (!ctx) throw new Error('AppProviderが必要')\n  return ctx\n}\n\`\`\`\n\n## まとめ\n\nuseReducerはアクションが明示的なので状態変更の追跡がしやすい。`,
    tags: JSON.stringify(['React', 'TypeScript', 'useReducer', 'Context', '状態管理']),
    advice: 'Zustandより軽量な選択肢として、外部ライブラリを増やしたくない場合に有効。',
    likes: 14,
  },
  {
    title: 'PythonのPolarsでPandasより10倍速いデータ処理を実現',
    summary: '大容量CSVの集計処理をPandasからPolarsに移行し、処理時間を45秒から4秒に短縮した経験をまとめた。',
    content: `## Pandasとの速度比較（100万行CSV）\n\n| 処理 | Pandas | Polars |\n|------|--------|--------|\n| 読み込み | 12s | 1.2s |\n| グループ集計 | 8s | 0.6s |\n| フィルタ | 5s | 0.3s |\n\n## Polarsの基本\n\n\`\`\`python\nimport polars as pl\n\n# 読み込み\ndf = pl.read_csv('large_data.csv')\n\n# Lazy評価（クエリプランを最適化してから実行）\nresult = (\n    pl.scan_csv('large_data.csv')  # scan_csvはLazy\n    .filter(pl.col('status') == 'active')\n    .group_by('category')\n    .agg([\n        pl.col('amount').sum().alias('total'),\n        pl.col('id').count().alias('count'),\n    ])\n    .sort('total', descending=True)\n    .collect()  # ここで実行\n)\n\`\`\`\n\n## まとめ\n\n大規模データ処理はPolarsが現時点で最も高速な選択肢の一つ。`,
    tags: JSON.stringify(['Python', 'Polars', 'データ処理', 'パフォーマンス', 'データ分析']),
    advice: 'scan_csvとlazyフレームを使うとPolarsのクエリオプティマイザが効いてさらに速くなる。',
    likes: 48,
  },
  {
    title: 'SentryでフロントエンドのエラーをリアルタイムにSlack通知',
    summary: 'Sentry SDKを導入してReactアプリの未捕捉エラーを自動でキャプチャし、Slackに通知する仕組みを構築した。',
    content: `## Sentry導入\n\n\`\`\`bash\nnpm install @sentry/nextjs\nnpx @sentry/wizard@latest -i nextjs\n\`\`\`\n\n## 設定\n\n\`\`\`typescript\n// sentry.client.config.ts\nimport * as Sentry from '@sentry/nextjs'\n\nSentry.init({\n  dsn: process.env.NEXT_PUBLIC_SENTRY_DSN,\n  environment: process.env.NODE_ENV,\n  tracesSampleRate: 0.1,  // 10%のトレースを収集\n  beforeSend(event) {\n    // 開発環境では送信しない\n    if (process.env.NODE_ENV === 'development') return null\n    return event\n  }\n})\n\`\`\`\n\n## エラーの手動キャプチャ\n\n\`\`\`typescript\ntry {\n  await riskyOperation()\n} catch (error) {\n  Sentry.captureException(error, {\n    extra: { userId, action: 'riskyOperation' }\n  })\n  throw error\n}\n\`\`\`\n\n## まとめ\n\nSentryを入れると「ユーザーから報告される前に」エラーを検知できる。`,
    tags: JSON.stringify(['Sentry', 'React', 'Next.js', 'エラー監視', 'TypeScript']),
    advice: 'tracesSampleRateは本番で0.1〜0.2にしないとコストが膨らむ。',
    likes: 28,
  },
  {
    title: 'TypeScriptのdiscriminated unionで状態管理を型安全に',
    summary: 'isLoading/isErrorフラグの組み合わせ爆発をdiscriminated unionで解消し、型安全な状態管理を実現した。',
    content: `## 問題のある設計\n\n\`\`\`typescript\n// フラグの組み合わせが爆発する\ntype State = {\n  data: Data | null\n  isLoading: boolean\n  isError: boolean\n  error: Error | null\n}\n// isLoading:true & isError:true のような矛盾した状態が表現できてしまう\n\`\`\`\n\n## discriminated unionで解決\n\n\`\`\`typescript\ntype State =\n  | { status: 'idle' }\n  | { status: 'loading' }\n  | { status: 'success'; data: Data }\n  | { status: 'error'; error: Error }\n\n// 使用\nfunction Component({ state }: { state: State }) {\n  switch (state.status) {\n    case 'loading': return <Spinner />\n    case 'error': return <ErrorMessage error={state.error} /> // errorは型安全\n    case 'success': return <DataView data={state.data} />    // dataは型安全\n    default: return null\n  }\n}\n\`\`\`\n\n## まとめ\n\ndiscriminated unionを使うとありえない状態を型レベルで排除できる。`,
    tags: JSON.stringify(['TypeScript', 'React', '型安全', 'フロントエンド']),
    advice: '\"Make impossible states impossible\" はTypeScriptを使う最大の理由の一つ。',
    likes: 44,
  },
  {
    title: 'AWS CDKでインフラをTypeScriptで管理する入門',
    summary: 'CloudFormationをそのまま書く代わりにCDKを使い、TypeScriptでタイプセーフにAWSインフラを定義した。',
    content: `## CDKのメリット\n\n- TypeScriptで書けるのでIDE補完が効く\n- ループや条件分岐でリソースを動的生成できる\n- L2コンストラクトで設定が簡潔になる\n\n## サンプル\n\n\`\`\`typescript\nimport * as cdk from 'aws-cdk-lib'\nimport * as ec2 from 'aws-cdk-lib/aws-ec2'\nimport * as ecs from 'aws-cdk-lib/aws-ecs'\n\nclass AppStack extends cdk.Stack {\n  constructor(scope: cdk.App, id: string) {\n    super(scope, id)\n\n    const vpc = new ec2.Vpc(this, 'AppVpc', { maxAzs: 2 })\n\n    const cluster = new ecs.Cluster(this, 'AppCluster', { vpc })\n\n    new ecs.FargateService(this, 'WebService', {\n      cluster,\n      taskDefinition: new ecs.FargateTaskDefinition(this, 'Task'),\n      desiredCount: 2,\n    })\n  }\n}\n\nnew AppStack(new cdk.App(), 'Production')\n\`\`\`\n\n## デプロイ\n\n\`\`\`bash\ncdk diff   # 変更内容確認\ncdk deploy # デプロイ\n\`\`\`\n\n## まとめ\n\nTerraformよりAWSに特化して書きやすい。AWSメインのチームに向いている。`,
    tags: JSON.stringify(['AWS', 'CDK', 'TypeScript', 'IaC', 'インフラ']),
    advice: 'CDKはL2/L3コンストラクトを優先使用するとコード量が激減する。',
    likes: 31,
  },
  {
    title: 'React Hook FormとZodでフォームバリデーションを型安全に',
    summary: 'zodスキーマからTypeScriptの型を自動生成しreact-hook-formと連携してランタイム・コンパイル時の両方でバリデーションを実現した。',
    content: `## 実装\n\n\`\`\`typescript\nimport { useForm } from 'react-hook-form'\nimport { zodResolver } from '@hookform/resolvers/zod'\nimport { z } from 'zod'\n\nconst schema = z.object({\n  email: z.string().email('正しいメールアドレスを入力してください'),\n  password: z.string().min(8, 'パスワードは8文字以上'),\n  age: z.number().min(18, '18歳以上である必要があります'),\n})\n\ntype FormData = z.infer<typeof schema>  // 型を自動生成\n\nexport function LoginForm() {\n  const { register, handleSubmit, formState: { errors } } = useForm<FormData>({\n    resolver: zodResolver(schema)\n  })\n\n  return (\n    <form onSubmit={handleSubmit(onSubmit)}>\n      <input {...register('email')} />\n      {errors.email && <p>{errors.email.message}</p>}\n      <button type="submit">送信</button>\n    </form>\n  )\n}\n\`\`\`\n\n## まとめ\n\nzod + react-hook-form + zodResolverの組み合わせはフロントエンドフォームの最強パターン。`,
    tags: JSON.stringify(['React', 'TypeScript', 'Zod', 'React Hook Form', 'バリデーション']),
    advice: 'zodスキーマはAPIのリクエスト/レスポンスバリデーションにも使い回せる。',
    likes: 47,
  },
  {
    title: 'Node.jsのCluster モードで複数CPUコアを活用してスループットを向上',
    summary: 'Node.jsはシングルスレッドだが、clusterモジュールでワーカーを並列起動しCPUを最大活用した。',
    content: `## 実装\n\n\`\`\`javascript\nconst cluster = require('cluster')\nconst numCPUs = require('os').cpus().length\n\nif (cluster.isPrimary) {\n  console.log(\`Primary \${process.pid} is running\`)\n\n  // CPUコア数分ワーカーを起動\n  for (let i = 0; i < numCPUs; i++) {\n    cluster.fork()\n  }\n\n  cluster.on('exit', (worker) => {\n    console.log(\`Worker \${worker.process.pid} died, restarting...\`)\n    cluster.fork()  // クラッシュしたワーカーを自動再起動\n  })\n} else {\n  // ワーカープロセス: 通常のExpressサーバー\n  const app = express()\n  app.listen(3000)\n  console.log(\`Worker \${process.pid} started\`)\n}\n\`\`\`\n\n## 本番ではPM2を推奨\n\n\`\`\`bash\npm2 start app.js -i max  # CPU数分クラスター起動\npm2 monit                # モニタリング\n\`\`\`\n\n## まとめ\n\nNode.jsでCPUバウンドな処理がある場合はclusterかWorker Threadsを検討する。`,
    tags: JSON.stringify(['Node.js', 'パフォーマンス', 'インフラ', 'PM2']),
    advice: 'I/Oバウンドなら非同期で十分。CPUバウンドな処理がある場合のみclusterが効果的。',
    likes: 19,
  },
  {
    title: 'ElasticsearchとMorphologicalAnalysisで日本語全文検索を実装',
    summary: '形態素解析プラグイン（analysis-kuromoji）を使ってElasticsearchで日本語の自然な全文検索を実現した。',
    content: `## プラグイン設定\n\n\`\`\`bash\n# kuromojiプラグインのインストール\nelasticsearch-plugin install analysis-kuromoji\n\`\`\`\n\n## インデックス設定\n\n\`\`\`json\n{\n  "settings": {\n    "analysis": {\n      "analyzer": {\n        "ja_analyzer": {\n          "type": "custom",\n          "tokenizer": "kuromoji_tokenizer",\n          "filter": ["kuromoji_baseform", "lowercase"]\n        }\n      }\n    }\n  },\n  "mappings": {\n    "properties": {\n      "title": { "type": "text", "analyzer": "ja_analyzer" },\n      "content": { "type": "text", "analyzer": "ja_analyzer" }\n    }\n  }\n}\n\`\`\`\n\n## クエリ\n\n\`\`\`json\n{\n  "query": {\n    "multi_match": {\n      "query": "データベース設計",\n      "fields": ["title^2", "content"],\n      "type": "best_fields"\n    }\n  }\n}\n\`\`\`\n\n## まとめ\n\nkuromojiで「データベース設計」を検索すると「データベース」「設計」に分かち書きされ自然な検索が可能になる。`,
    tags: JSON.stringify(['Elasticsearch', '全文検索', '日本語', 'インフラ']),
    advice: 'synonymsフィルターで類義語（「DB」→「データベース」）も設定すると検索精度が上がる。',
    likes: 33,
  },
  {
    title: 'Auth.jsでGoogle/GitHubのOAuth認証を15分で実装',
    summary: 'Next.js App RouterにAuth.js（旧NextAuth.js v5）を導入してソーシャルログインを最短で実装した手順。',
    content: `## インストール\n\n\`\`\`bash\nnpm install next-auth@beta\n\`\`\`\n\n## 設定\n\n\`\`\`typescript\n// auth.ts\nimport NextAuth from 'next-auth'\nimport Google from 'next-auth/providers/google'\nimport GitHub from 'next-auth/providers/github'\n\nexport const { handlers, signIn, signOut, auth } = NextAuth({\n  providers: [\n    Google,\n    GitHub,\n  ],\n})\n\`\`\`\n\n\`\`\`typescript\n// app/api/auth/[...nextauth]/route.ts\nimport { handlers } from '@/auth'\nexport const { GET, POST } = handlers\n\`\`\`\n\n## 使用方法\n\n\`\`\`typescript\n// Server Component\nimport { auth } from '@/auth'\n\nexport default async function Page() {\n  const session = await auth()\n  if (!session) redirect('/login')\n  return <div>こんにちは、{session.user?.name}</div>\n}\n\`\`\`\n\n## まとめ\n\nAuth.jsを使うとOAuth認証を自分で実装する必要がなく、数十行で実現できる。`,
    tags: JSON.stringify(['Next.js', 'Auth.js', 'OAuth', 'TypeScript', '認証']),
    advice: '環境変数はAUTH_SECRETとAUTH_GOOGLE_ID/SECRETが最低限必要。',
    likes: 56,
  },
  {
    title: 'Zodでランタイムバリデーションとスキーマ共有を実現',
    summary: 'フロントエンドとバックエンドで同じzodスキーマを共有することでAPI型の整合性を保つ設計パターンをまとめた。',
    content: `## スキーマ共有の設計\n\n\`\`\`typescript\n// shared/schemas.ts（フロント・バック共通）\nimport { z } from 'zod'\n\nexport const CreatePostSchema = z.object({\n  title: z.string().min(1).max(100),\n  content: z.string().min(10),\n  tags: z.array(z.string()).min(1).max(5),\n})\n\nexport type CreatePostInput = z.infer<typeof CreatePostSchema>\n\`\`\`\n\n\`\`\`typescript\n// APIルート（バックエンド）\nexport async function POST(req: Request) {\n  const body = await req.json()\n  const result = CreatePostSchema.safeParse(body)\n  if (!result.success) {\n    return Response.json({ error: result.error.flatten() }, { status: 400 })\n  }\n  const data = result.data  // 型安全なデータ\n  await db.post.create({ data })\n}\n\`\`\`\n\n\`\`\`typescript\n// フォーム（フロントエンド）\nconst form = useForm<CreatePostInput>({\n  resolver: zodResolver(CreatePostSchema)\n})\n\`\`\`\n\n## まとめ\n\nスキーマをmonorepoやsharedパッケージに置くとフロント・バックで型が一致する。`,
    tags: JSON.stringify(['Zod', 'TypeScript', 'React', 'API', 'バリデーション']),
    advice: 'zodのsafeParseはエラー時に例外を投げないのでAPIバリデーションに向いている。',
    likes: 38,
  },
  {
    title: 'Dockerfileのベストプラクティスまとめ',
    summary: 'セキュリティ・キャッシュ効率・サイズ最適化の観点でDockerfileを改善するポイントを体系的にまとめた。',
    content: `## 改善前\n\n\`\`\`dockerfile\nFROM node:20\nCOPY . .\nRUN npm install\nRUN npm run build\nCMD ["npm", "start"]\n\`\`\`\n\n## 改善後\n\n\`\`\`dockerfile\n# ①alpineで軽量化\nFROM node:20-alpine AS deps\nWORKDIR /app\n\n# ②package.jsonを先にコピー（キャッシュ活用）\nCOPY package*.json ./\nRUN npm ci --production\n\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine AS runner\nWORKDIR /app\n\n# ③rootユーザーを避けてセキュリティ向上\nRUN addgroup -S appgroup && adduser -S appuser -G appgroup\nUSER appuser\n\nCOPY --from=deps /app/node_modules ./node_modules\nCOPY --from=builder /app/dist ./dist\n\nEXPOSE 3000\nCMD ["node", "dist/index.js"]\n\`\`\`\n\n## 改善ポイント\n\n1. package.jsonを先にコピーしてキャッシュを活用\n2. マルチステージでビルドツールを除外\n3. rootユーザーで動かさない\n4. alpine使用で軽量化\n\n## まとめ\n\nDockerfileは一度書いたら見直す習慣を。`,
    tags: JSON.stringify(['Docker', 'セキュリティ', 'インフラ', 'パフォーマンス', 'ベストプラクティス']),
    advice: '.dockerignoreも忘れずに設定する。node_modulesと.envを除外するのが最低限。',
    likes: 41,
  },
  {
    title: 'GitHub Copilotを現場で効果的に使うコツ',
    summary: '3ヶ月間GitHub Copilotを使ってみて生産性が上がった使い方・気をつけるべき点をまとめた。',
    content: `## 効果的な使い方\n\n### 1. コメントで意図を伝える\n\n\`\`\`typescript\n// ユーザーのメールアドレスを検証し、形式が正しければtrue、そうでなければエラーメッセージを返す関数\nfunction validateEmail(email: string): true | string {\n  // ← ここでCopilotが実装を提案してくれる\n}\n\`\`\`\n\n### 2. テストコードの生成が特に強力\n\n\`\`\`typescript\n// validateEmailのテストを書く\ndescribe('validateEmail', () => {\n  // ← ここでCopilotがテストケースを全部書いてくれる\n})\n\`\`\`\n\n### 3. 繰り返しパターンの補完\n\n似たコードを1つ書いた後の続きを書くのが最も効率的。\n\n## 気をつけること\n\n- **セキュリティ関連のコードは必ずレビュー**（古いパターンを提案することがある）\n- **テストを書かずに信頼しない**（動くように見えて間違うことがある）\n- **APIの最新バージョンを知らない場合がある**\n\n## まとめ\n\nCopilotはスマートな補完ツール。生成コードを理解した上で使うのが正しい付き合い方。`,
    tags: JSON.stringify(['GitHub Copilot', 'AI', '開発効率', 'ツール']),
    advice: 'Copilotの提案は常にレビューする。コードの意味を理解せずに受け入れると負債になる。',
    likes: 29,
  },
  {
    title: 'Fastifyを使ってExpressより3倍速いAPIサーバーを構築',
    summary: 'ExpressからFastifyに移行してAPIのスループットを大幅に改善した。型安全なルーティングも紹介。',
    content: `## Fastifyの特徴\n\n- Express比で約3倍高速（JSON処理が特に速い）\n- TypeScriptとの親和性が高い\n- スキーマ定義でバリデーションと型が自動化\n\n## 実装\n\n\`\`\`typescript\nimport Fastify from 'fastify'\nimport { Type } from '@sinclair/typebox'\n\nconst app = Fastify({ logger: true })\n\n// スキーマ定義でバリデーション + 型安全\nconst UserSchema = Type.Object({\n  name: Type.String({ minLength: 1 }),\n  age: Type.Number({ minimum: 0 }),\n})\n\napp.post('/users', {\n  schema: {\n    body: UserSchema,\n    response: {\n      201: Type.Object({ id: Type.String() })\n    }\n  }\n}, async (request, reply) => {\n  const { name, age } = request.body  // 型が効く\n  const user = await createUser(name, age)\n  return reply.code(201).send({ id: user.id })\n})\n\nawait app.listen({ port: 3000 })\n\`\`\`\n\n## まとめ\n\n新規APIサーバーはFastifyを第一候補に検討する価値がある。`,
    tags: JSON.stringify(['Fastify', 'Node.js', 'TypeScript', 'API', 'パフォーマンス']),
    advice: 'Fastifyのpluginシステムを使うと認証・DB接続をカプセル化できてクリーンになる。',
    likes: 24,
  },
  {
    title: 'CSS :has()セレクタで親要素のスタイルを子の状態で変える',
    summary: 'CSS :has()が主要ブラウザで使えるようになりJavaScript不要で複雑な条件スタイルが実現できるようになった。',
    content: `## 使用例\n\n\`\`\`css\n/* チェックボックスがチェックされたら親カードを強調 */\n.card:has(input[type="checkbox"]:checked) {\n  border-color: var(--cyan-500);\n  background: var(--cyan-50);\n}\n\n/* フォームにエラーがあれば送信ボタンを変える */\nform:has(.error-message:not(:empty)) button[type="submit"] {\n  opacity: 0.5;\n  cursor: not-allowed;\n}\n\n/* 画像がある場合とない場合でレイアウトを変える */\n.article:has(img) {\n  display: grid;\n  grid-template-columns: 1fr 300px;\n}\n\n.article:not(:has(img)) {\n  max-width: 700px;\n}\n\`\`\`\n\n## ブラウザサポート\n\nChrome 105+, Safari 15.4+, Firefox 121+で使用可能（2024年時点で主要ブラウザ対応済み）\n\n## まとめ\n\n:has()は「親セレクタ」として長年待望されていた機能。CSSだけで解決できる範囲が大幅に広がった。`,
    tags: JSON.stringify(['CSS', 'フロントエンド', 'セレクタ', 'ブラウザ']),
    advice: ':has()はパフォーマンスへの影響を考慮して過度に使いすぎないよう注意。',
    likes: 20,
  },
  {
    title: 'Prometheusでカスタムメトリクスを収集してGrafanaで可視化',
    summary: 'Node.jsアプリにprom-clientを導入して独自メトリクスを計測し、Grafanaダッシュボードで監視できるようにした。',
    content: `## prom-client実装\n\n\`\`\`typescript\nimport { Registry, Counter, Histogram } from 'prom-client'\n\nconst registry = new Registry()\n\n// カウンター（単調増加）\nconst httpRequestsTotal = new Counter({\n  name: 'http_requests_total',\n  help: 'Total HTTP requests',\n  labelNames: ['method', 'status_code', 'path'],\n  registers: [registry],\n})\n\n// ヒストグラム（レイテンシ計測）\nconst requestDuration = new Histogram({\n  name: 'http_request_duration_seconds',\n  help: 'HTTP request duration in seconds',\n  buckets: [0.01, 0.05, 0.1, 0.3, 0.5, 1, 2, 5],\n  registers: [registry],\n})\n\n// ミドルウェア\napp.use(async (req, res, next) => {\n  const end = requestDuration.startTimer()\n  res.on('finish', () => {\n    httpRequestsTotal.labels(req.method, String(res.statusCode), req.path).inc()\n    end({ method: req.method, status_code: String(res.statusCode) })\n  })\n  next()\n})\n\n// /metricsエンドポイント\napp.get('/metrics', async (req, res) => {\n  res.set('Content-Type', registry.contentType)\n  res.send(await registry.metrics())\n})\n\`\`\`\n\n## まとめ\n\nPrometheus + Grafanaの組み合わせはOSSの監視スタックの定番。`,
    tags: JSON.stringify(['Prometheus', 'Grafana', 'Node.js', '監視', 'インフラ', 'DevOps']),
    advice: 'メトリクスの命名はPrometheusの命名規則（snake_case + _total/_seconds等のサフィックス）に従う。',
    likes: 36,
  },
  {
    title: 'tRPCでフルスタックTypeScriptのエンドツーエンド型安全を実現',
    summary: 'REST APIの型定義の重複をtRPCで解消し、サーバー・クライアント間で型が自動的に共有される環境を構築した。',
    content: `## tRPCとは\n\nAPIの型定義を一箇所に書くだけでフロントエンドに型が自動的に共有される。\n\n## 実装\n\n\`\`\`typescript\n// server/router.ts\nimport { initTRPC } from '@trpc/server'\nimport { z } from 'zod'\n\nconst t = initTRPC.create()\n\nexport const appRouter = t.router({\n  user: t.router({\n    getById: t.procedure\n      .input(z.string())\n      .query(async ({ input: id }) => {\n        return db.user.findUnique({ where: { id } })\n      }),\n    create: t.procedure\n      .input(z.object({ name: z.string(), email: z.string().email() }))\n      .mutation(async ({ input }) => {\n        return db.user.create({ data: input })\n      }),\n  }),\n})\n\nexport type AppRouter = typeof appRouter\n\`\`\`\n\n\`\`\`typescript\n// クライアント\nimport { createTRPCReact } from '@trpc/react-query'\nimport type { AppRouter } from '../server/router'\n\nconst trpc = createTRPCReact<AppRouter>()\n\n// 型安全なAPIコール\nconst user = trpc.user.getById.useQuery('user-id-123')\nconst createUser = trpc.user.create.useMutation()\n\`\`\`\n\n## まとめ\n\ntRPCはNext.jsフルスタックアプリで最も型安全なAPI設計を実現できる。`,
    tags: JSON.stringify(['tRPC', 'TypeScript', 'Next.js', 'React', 'API', 'フルスタック']),
    advice: 'tRPCはNext.jsのMonorepoプロジェクトで特に威力を発揮する。',
    likes: 53,
  },
  {
    title: 'Linuxのsystemdでアプリをサービス化して自動起動させる',
    summary: 'Node.jsアプリをsystemdのサービスとして登録し、OS起動時の自動起動とクラッシュ時の自動再起動を設定した。',
    content: `## サービスファイルの作成\n\n\`\`\`bash\nsudo nano /etc/systemd/system/myapp.service\n\`\`\`\n\n\`\`\`ini\n[Unit]\nDescription=My Node.js Application\nAfter=network.target\n\n[Service]\nType=simple\nUser=ubuntu\nWorkingDirectory=/home/ubuntu/app\nExecStart=/usr/bin/node dist/index.js\nRestart=on-failure\nRestartSec=10\nEnvironmentFile=/home/ubuntu/app/.env\n\n[Install]\nWantedBy=multi-user.target\n\`\`\`\n\n## 有効化と起動\n\n\`\`\`bash\nsudo systemctl daemon-reload\nsudo systemctl enable myapp   # OS起動時に自動起動\nsudo systemctl start myapp    # 今すぐ起動\nsudo systemctl status myapp   # 状態確認\njournalctl -u myapp -f        # ログ確認\n\`\`\`\n\n## まとめ\n\nPM2よりシンプルな環境ではsystemdで十分。OS標準機能なので追加インストール不要。`,
    tags: JSON.stringify(['Linux', 'systemd', 'Node.js', 'インフラ', 'サーバー']),
    advice: 'EnvironmentFileで.envを読み込むとシークレットをサービスファイルに書かずに済む。',
    likes: 16,
  },
  {
    title: 'BunでNode.jsより3倍速いTypeScriptサーバーを動かす',
    summary: 'BunをJavaScriptランタイムとして採用してNode.jsベースのAPIサーバーを移行し、起動時間とスループットを改善した。',
    content: `## Bunの特徴\n\n- Node.jsより起動が速い（ウォームアップが不要）\n- TypeScriptをトランスパイルなしで直接実行\n- npm互換のパッケージマネージャー内蔵\n- HTTPサーバーのスループットがNode.jsの約3倍\n\n## Bunのネイティブサーバー\n\n\`\`\`typescript\n// server.ts\nBun.serve({\n  port: 3000,\n  async fetch(req) {\n    const url = new URL(req.url)\n\n    if (url.pathname === '/api/users') {\n      const users = await db.user.findMany()\n      return Response.json(users)\n    }\n\n    return new Response('Not Found', { status: 404 })\n  }\n})\n\n// 実行\n// bun run server.ts  ← TypeScriptそのまま実行\n\`\`\`\n\n## 移行の注意点\n\n- 一部Node.js固有APIは使えない\n- まだ本番での実績は少ない\n- Prismaは対応済み（Bun compatible）\n\n## まとめ\n\nBunはエッジ・サーバーレス環境での高速化に有望。本番採用は慎重に。`,
    tags: JSON.stringify(['Bun', 'TypeScript', 'Node.js', 'パフォーマンス', 'ランタイム']),
    advice: 'Bunはまだ本番事例が少ない。社内ツールやsideプロジェクトで試してから判断する。',
    likes: 42,
  },
  {
    title: 'Gitのhookとlint-stagedで壊れたコードをコミットできないようにする',
    summary: 'pre-commitフックでテストとlintを強制実行し、CIで失敗するコードをローカルでブロックする仕組みを作った。',
    content: `## 設定\n\n\`\`\`bash\nnpm install --save-dev husky lint-staged\nnpx husky init\n\`\`\`\n\n\`\`\`bash\n# .husky/pre-commit\n#!/bin/sh\nnpx lint-staged\n\`\`\`\n\n\`\`\`json\n// package.json\n{\n  "lint-staged": {\n    "*.{ts,tsx}": [\n      "eslint --fix --max-warnings 0",\n      "prettier --write",\n      "bash -c 'npx tsc --noEmit'"\n    ],\n    "*.test.{ts,tsx}": [\n      "jest --bail --findRelatedTests"\n    ]\n  }\n}\n\`\`\`\n\n## --max-warnings 0 の理由\n\nwarningを0にしないと「警告があっても通過」してしまい意味がなくなる。\n\n## まとめ\n\nコミット時にローカルでチェックするとCIを待たずに問題がわかる。開発サイクルが速くなる。`,
    tags: JSON.stringify(['Git', 'husky', 'ESLint', 'CI/CD', '開発効率', 'TypeScript']),
    advice: 'huskyのhookはチームメンバーがnpm installした時に自動でセットアップされる（prepare scriptを設定）。',
    likes: 21,
  },
]

async function main() {
  console.log('Seeding database...')

  // 既存データを削除
  await prisma.message.deleteMany()
  await prisma.post.deleteMany()

  const now = new Date()

  for (let i = 0; i < posts.length; i++) {
    const post = posts[i]
    const author = authors[i % authors.length]
    // 過去3ヶ月以内のランダムな日時
    const daysAgo = Math.floor(Math.random() * 90)
    const createdAt = new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000)

    await prisma.post.create({
      data: {
        authorName: author,
        rawInput: post.content.slice(0, 200),
        title: post.title,
        summary: post.summary,
        content: post.content,
        tags: post.tags,
        advice: post.advice,
        likes: post.likes,
        createdAt,
      },
    })
    process.stdout.write(`\r${i + 1}/${posts.length} 件投入済み`)
  }

  console.log('\nDone!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
